Feature/database refactor
Lambda-School-Labs/Express_Groomer-TeamB-BE pull request #21
Opened 2021-01-07 23:35 UTC by riddlej9879

## Description ##

DESCRIBE YOUR PULL REQUEST'S CHANGES AND REFERENCE THE FEATURE/USERSTORY/BUG IT'S REALATED TO.  REPLACE THIS TEXT.
The database has been refactored. The migration and seed tables have been separated out into their own files to be easier to maintain in the future. Pet_types table has been removed from the database.

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.
- [*] This is a refactor

## Organization ##

- [*] Have you linked this pull request to a Trello card?
- [*] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [*] Is this ready to be reviewed?
- [*] Have you added two reviewers to this pull request?

2021-01-08 00:29 UTC, JessBonanno requested changes
- Josh, I was unable to get the server running on my local machine and I notice the checks are not passing.  I am getting this error in my console:

 if (arguments.length === 0 || (!config.client && !config.dialect)) {
                                         ^
TypeError: Cannot read property 'client' of undefined

- I also noticed you commented out some of the original code in the create-profile model, unsure why,
- The pet-types model still exists and just contains the following.. should we just remove this entire migration file?
exports.up = async (knex) => {};
exports.down = async function (knex) {};
- There is also a customer-pets-types table.. this is spelled differently from the original "customer_pets_type", is there a reason and does this break anything? Can we drop this table altogether?
- Can we drop the groomer-schedule table?  It only has an id, I don't think we need this for anything.

2021-01-08 02:06 UTC, JessicaGCooper commented on data/migrations/0001_create-profile.js
> +      // Error: CREATE EXTENSION IF NOT EXISTS "uuid-ossp" - SQLITE_ERROR: near "EXTENSION": syntax error
I don't think we should change this table to exclude the Create Extension, this is part of the original code provided to relate to Okta, which I know you would not have any reason to know.  This line is compatible with PostgreSql so it's only using Sqlite which is causing the error.

2021-01-08 02:07 UTC, JessicaGCooper commented on data/migrations/0004_pet-types.js
> +exports.up = async (knex) => {};
This entire file will need to be deleted.

2021-01-08 02:08 UTC, JessicaGCooper commented on data/migrations/0005_pets.js
> +    // table.bigint('pet_types_id').references('id').inTable('pet_types');
Since the pet_types table is completely removed from the schema this commented out code can be removed.

2021-01-08 02:11 UTC, JessicaGCooper commented on data/seeds/000_truncate.js
> -  await knex.raw('TRUNCATE TABLE profiles CASCADE');
We'll have to use cascade to truncate any table that involve a foreign key.  Again that format is compatible with PostgreSql.

2021-01-09 01:53 UTC, closed without merging

2021-01-09 01:53 UTC, JessBonanno commented
Closing this branch to start fresh

2021-02-05 00:26 UTC, JessicaGCooper commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor migrations on Back-End so that each table has it's own migration file.](https://trello.com/c/hT8rYKrb/20-refactor-migrations-on-back-end-so-that-each-table-has-its-own-migration-file)